apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-info
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-info
  template:
    metadata:
      labels:
        app: blog-info
    spec:
      containers:
      - image: making/blog-info
        name: blog-info
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "32Mi"
          requests:
            memory: "16Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: blog-info
  namespace: blog
  labels:
    app: blog-info
spec:
  selector:
    app: blog-info
  ports:
  - protocol: TCP
    port: 8080
    name: http
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: blog-info
  path: .
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: blog-info
  newImage: making/blog-info
---
apiVersion: gateway.cloud.ik.am/v1beta1
kind: RouteDefinition
metadata:
  name: blog-info
  namespace: blog
spec:
  route:
    predicates:
    - Host=info.ik.am
    filters:
    - RequestLogging=